# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HEK_Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noaaNmbr', models.CharField(default=0, max_length=40, verbose_name='Noaa Number')),
                ('dateAndTime', models.DateTimeField(max_length=40, verbose_name='Date And Time')),
                ('xcen', models.FloatField(default=0, max_length=40, verbose_name='X-Cen')),
                ('ycen', models.FloatField(default=0, max_length=40, verbose_name='Y-Cen')),
                ('xfov', models.FloatField(default=0, max_length=40, verbose_name='X-FOV')),
                ('yfov', models.FloatField(default=0, max_length=40, verbose_name='Y-FOV')),
                ('sciObj', models.CharField(default='None recorded', max_length=100, verbose_name='Science Observations')),
            ],
        ),
    ]
